language: node_js
dist: xenial
sudo: required

node_js:
  - "10"

addons:
  apt:
    packages:
      - libluajit-5.1-dev

script:
  - npm run lint
  - npm run test/coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    on_success: change
    on_failure: always
