language: node_js

sudo: false

node_js:
  - "10"

env:
  global:
    - LUAROCKS=2.3.0
    - LUA=luajit

before_install:
  - source .travis/setenv_lua.sh
  - ls /usr/local/lib

script:
  - npm run lint
  - npm run test/coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    on_success: change
    on_failure: always
