language: node_js

node_js:
  - "10"

before_install:
  - find /usr/include /usr/local/include $NODELUA_INCLUDE -name lua.h | sed s/lua.h// | sort | head -n 1
  - find /usr/lib /usr/local/lib /usr/include /usr/local/include $NODELUA_LIB -name libluajit-5.1.so | tail -n 1

script:
  - npm run lint
  - npm run test/coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
