const acquisitions = {
  ALERTS: 'Alerts',
  ANNIVERSARY: 'Anniversary',
  BARO_KITEER: 'Baro Ki\'Teer',
  BIO_LAB: 'Bio Lab (Dojo)',
  CEPHALON_SIMARIS: 'Cephalon Simaris',
  CETUS_BOUNTY_40_60: 'Cetus Bounty (Levels 40 - 60)',
  CETUS_BOUNTY_GHOUL: 'Cetus Bounty (Ghoul)',
  CHEM_LAB: 'Chem Lab (Dojo)',
  ENERGY_LAB: 'Energy Lab (Dojo)',
  FOMORIAN_SABOTAGE: 'Fomorian Sabotage',
  GRUSTRAG_THREE: 'The Grustrag Three',
  HOKS_ANVIL: 'Hok\'s Anvil (Cetus)',
  INCUBATOR_SEGMENT: 'Incubator Segment',
  INVASIONS: 'Invasions',
  LOGIN_REWARD: 'Login Reward',
  MARKET: 'Market',
  OPERATION_PLAGUE_STAR: 'Operation Plague Star',
  OROKIN_LAB: 'Orokin Lab (Dojo)',
  RAZORBACK_ARMADA: 'Razorback Armada',
  RELICS: 'Relics',
  SANCTUARY_ONSLAUGHT: 'Sanctuary Onslaught',
  SPY_MISSIONS: 'Spy Missions',
  STALKER: 'Stalker',
  THE_QUILLS: 'The Quills (Cetus)',
  TENNO_LAB: 'Tenno Lab (Dojo)',
  UNOBTAINABLE: 'Unobtainable',
  VAULTED: 'Vaulted',
};

const acquisitionQuests = {
  CHAINS_OF_HARROW: 'Chains of Harrow (Quest)',
  HIDDEN_MESSAGES: 'Hidden Messages (Quest)',
  OCTAVIAS_ANTHEM: 'Octavia\'s Anthem (Quest)',
  SANDS_OF_INAROS: 'Sands of Inaros (Quest)',
  SAYAS_VIGIL: 'Saya\'s Vigil (Quest)',
  THE_ARCHWING: 'The Archwing (Quest)',
  THE_GLAST_GAMBIT: 'The Glast Gambit (Quest)',
  THE_LIMBO_THEOREM: 'The Limbo Theorem (Quest)',
  THE_NEW_STRANGE: 'The New Strange (Quest)',
  THE_SECOND_DREAM: 'The Second Dream (Quest)',
  THE_SILVER_GROVE: 'The Silver Grove (Quest)',
  THE_WAR_WITHIN: 'The War Within (Quest)',
};

const acquisitionFactions = {
  ARBITERS_OF_HEXIS: 'Arbiters of Hexis (Maxim)',
  CEPHALON_SUDA: 'Cephalon Suda (Genius)',
  NEW_LOKA: 'New Loka (Flawless)',
  RED_VEIL: 'Red Veil (Exalted)',
  STEEL_MERIDIAN: 'Steel Meridian (General)',
  THE_PERRIN_SEQUENCE: 'The Perrin Sequence (Partner)',
};

const acquisitionEnemies = {
  ALAD_V: 'Alad V (Boss)',
  AMBULAS: 'Ambulas (Boss)',
  DREKAR_TROOPERS: 'Drekar Troopers',
  EXIMUS_ENEMIES: 'Eximus Enemies',
  HEAVY_GUNNERS: 'Heavy Gunners',
  HYENA_PACK: 'Hyena Pack (Boss)',
  JACKAL: 'Jackal (Boss)',
  JORDAS_GOLEM: 'Jordas Golem (Boss)',
  KELA_DE_THAYM: 'Kela De Thaym (Boss)',
  LECH_KRILL: 'Lieutenant Lech Kril (Boss)',
  LEPHANTIS: 'Lephantis (Boss)',
  MANICS: 'Manics',
  MUTALIST_ALAD_V: 'Mutalist Alad V (Boss)',
  PHORID: 'Phorid (Boss)',
  SARGAS_RUK: 'General Sargas Ruk (Boss)',
  THE_RAPTORS: 'The Raptors (Boss)',
  TYL_REGOR: 'Tyl Regor (Boss)',
  THE_SERGEANT: 'The Sergeant (Boss)',
  VOR_AND_KRILL: 'Captain Vor and Lieutenant Lech Kril (Boss Duo)',
  VAY_HEK: 'Councilor Vay Hek (Boss)',
  VOR: 'Captain Vor (Boss)',
};

const primaryCategories = {
  BOW: 'Bow',
  LAUNCHER: 'Launcher',
  RIFLE: 'Rifle',
  SHOTGUN: 'Shotgun',
  SNIPER: 'Sniper',
  SPEARGUN: 'Speargun',
};

const secondaryCategories = {
  DUAL_PISTOLS: 'Dual Pistols',
  SINGLE_PISTOL: 'Single Pistol',
  THROWN: 'Thrown',
};

const meleeCategories = {
  BLADE_WHIP: 'Blade-Whip',
  CLAWS: 'Claws',
  DAGGER: 'Dagger',
  DUAL_DAGGERS: 'Dual Daggers',
  DUAL_SWORDS: 'Dual Swords',
  FIST: 'Fist',
  GLAIVE: 'Glaive',
  GUNBLADE: 'Gunblade',
  HAMMER: 'Hammer',
  HEAVY_BLADE: 'Heavy Blade',
  HYBRID: 'Hybrid',
  MACHETE: 'Machete',
  NIKANA: 'Nikana',
  NUNCHAKU: 'Nunchaku',
  POLEARM: 'Polearm',
  RAPIER: 'Rapier',
  SCYTHE: 'Scythe',
  SPARRING: 'Sparring',
  STAFF: 'Staff',
  SWORD: 'Sword',
  SWORD_SHEILD: 'Sword-Shield',
  TONFA: 'Tonfa',
  WARFANS: 'Warfans',
  WHIP: 'Whip',
};

const itemTypes = {
  AMP: 'Amp',
  ARCHWING: 'Archwing',
  ARCHWING_GUN: 'Archwing Gun',
  ARCHWING_MELEE: 'Archwing Melee',
  COMPANION_SENTINEL: 'Sentinel',
  COMPANION_KUBROW: 'Kubrow',
  COMPANION_KAVAT: 'Kavat',
  SENTINEL_WEAPON: 'Sentinel Weapon',
  WARFRAME: 'Warframe',
  WEAPON_PRIMARY: 'Primary Weapon',
  WEAPON_SECONDARY: 'Secondary Weapon',
  WEAPON_MELEE: 'Melee Weapon',
  ZAW: 'Zaw',
};

module.exports = {
  acquisitions,
  acquisitionQuests,
  acquisitionFactions,
  acquisitionEnemies,
  primaryCategories,
  secondaryCategories,
  meleeCategories,
  itemTypes,
};
